// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Galaxis

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void search_anim_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_SplashLabel;


// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
lv_obj_t * ui_MainMenu;
lv_obj_t * ui_MainMenuItem;
lv_obj_t * ui_MainMenuHint;


// SCREEN: ui_Game
void ui_Game_screen_init(void);
lv_obj_t * ui_Game;
lv_obj_t * ui_GamePanel;
lv_obj_t * ui_Connected;
lv_obj_t * ui_StatusLabel;
lv_obj_t * ui_SearchResult;
lv_obj_t * ui_CoordinatesX;
lv_obj_t * ui_CoordinatesY;


// SCREEN: ui_GameOver
void ui_GameOver_screen_init(void);
lv_obj_t * ui_GameOver;
lv_obj_t * ui_GameOverItem;
lv_obj_t * ui_GameOverHint;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_bg[1] = {&ui_img_bg2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void search_anim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 5);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_MainMenu_screen_init();
    ui_Game_screen_init();
    ui_GameOver_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
