// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Galaxis

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t *ui_SplashScreen;
lv_obj_t *ui_SplashLabel;


// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
lv_obj_t *ui_MainMenu;
lv_obj_t *ui_MainMenuPanel;
lv_obj_t *ui_MainMenuItem;
lv_obj_t *ui_MainMenuHint;


// SCREEN: ui_Game
void ui_Game_screen_init(void);
lv_obj_t *ui_Game;
lv_obj_t *ui_GamePanel;
lv_obj_t *ui_Coordinates;
lv_obj_t *ui_StatusLabel;
lv_obj_t *ui_SearchResult;
lv_obj_t *ui_ShipCount;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_SplashScreen_screen_init();
ui_MainMenu_screen_init();
ui_Game_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_SplashScreen);
}
