//
// Created by jmartens on 05.11.2023.
//

#ifndef GALAXIS_SCREEN_H
#define GALAXIS_SCREEN_H

enum Screen {
    NO_CHANGE, MENU, PERIPHERAL_GAME, CENTRAL_GAME, GAME_OVER_SCREEN, WINNER_SCREEN, SETTINGS
};
#endif //GALAXIS_SCREEN_H
