// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Galaxis

#ifndef UI_GAMEOVER_H
#define UI_GAMEOVER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GameOver
extern void ui_GameOver_screen_init(void);
extern void ui_GameOver_screen_destroy(void);
extern lv_obj_t * ui_GameOver;
extern lv_obj_t * ui_GameOverItem;
extern lv_obj_t * ui_GameOverHint;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

