// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Galaxis

#include "../ui.h"

void ui_GameOver_screen_init(void)
{
ui_GameOver = lv_obj_create(NULL);
lv_obj_clear_flag( ui_GameOver, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_GameOverPanel = lv_obj_create(ui_GameOver);
lv_obj_set_width( ui_GameOverPanel, 225);
lv_obj_set_height( ui_GameOverPanel, 225);
lv_obj_set_align( ui_GameOverPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_GameOverPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_GameOverPanel, 115, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_GameOverPanel, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_GameOverPanel, 152, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_GameOverPanel, 152, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_GameOverPanel, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GameOverPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GameOverItem = lv_label_create(ui_GameOverPanel);
lv_obj_set_width( ui_GameOverItem, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GameOverItem, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GameOverItem, 0 );
lv_obj_set_y( ui_GameOverItem, -25 );
lv_obj_set_align( ui_GameOverItem, LV_ALIGN_CENTER );
lv_label_set_text(ui_GameOverItem,"Game over");
lv_obj_set_style_text_color(ui_GameOverItem, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GameOverItem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_GameOverItem, &ui_font_Destruct36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GameOverHint = lv_label_create(ui_GameOverPanel);
lv_obj_set_width( ui_GameOverHint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GameOverHint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GameOverHint, 0 );
lv_obj_set_y( ui_GameOverHint, 39 );
lv_obj_set_align( ui_GameOverHint, LV_ALIGN_CENTER );
lv_label_set_text(ui_GameOverHint,"");

}
