// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Galaxis

#ifndef UI_GAME_H
#define UI_GAME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Game
extern void ui_Game_screen_init(void);
extern void ui_Game_screen_destroy(void);
extern lv_obj_t * ui_Game;
extern lv_obj_t * ui_SearchResult;
extern lv_obj_t * ui_Coordinates;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_Connected;
extern lv_obj_t * ui_Round;
extern lv_obj_t * ui_ElapsedTime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

