// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Galaxis

#ifndef UI_HIDESHIPS_H
#define UI_HIDESHIPS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HideShips
extern void ui_HideShips_screen_init(void);
extern void ui_HideShips_screen_destroy(void);
extern lv_obj_t * ui_HideShips;
extern lv_obj_t * ui_okButton1;
extern lv_obj_t * ui_okButtonLabel1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_HideInfo;
extern lv_obj_t * ui_Ship1;
extern lv_obj_t * ui_Ship2;
extern lv_obj_t * ui_Ship3;
extern lv_obj_t * ui_Ship4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

