// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Galaxis

#include "../ui.h"

lv_obj_t * ui_HideShips = NULL;
lv_obj_t * ui_okButton1 = NULL;
lv_obj_t * ui_okButtonLabel1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_HideInfo = NULL;
lv_obj_t * ui_Ship1 = NULL;
lv_obj_t * ui_Ship2 = NULL;
lv_obj_t * ui_Ship3 = NULL;
lv_obj_t * ui_Ship4 = NULL;
// event funtions

// build funtions

void ui_HideShips_screen_init(void)
{
    ui_HideShips = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HideShips, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okButton1 = lv_btn_create(ui_HideShips);
    lv_obj_set_width(ui_okButton1, 100);
    lv_obj_set_height(ui_okButton1, 25);
    lv_obj_set_x(ui_okButton1, 0);
    lv_obj_set_y(ui_okButton1, 49);
    lv_obj_set_align(ui_okButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_okButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_okButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_okButton1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_okButton1, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_okButtonLabel1 = lv_label_create(ui_okButton1);
    lv_obj_set_width(ui_okButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_okButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_okButtonLabel1, "OK");

    ui_Container2 = lv_obj_create(ui_HideShips);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 158);
    lv_obj_set_height(ui_Container2, 101);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -22);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HideInfo = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_HideInfo, 158);
    lv_obj_set_height(ui_HideInfo, 35);
    lv_obj_set_align(ui_HideInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HideInfo, "Hide ships and \npress OK");
    lv_obj_clear_flag(ui_HideInfo, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_align(ui_HideInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ship1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Ship1, 75);
    lv_obj_set_height(ui_Ship1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ship1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ship1, "A1");
    lv_obj_add_flag(ui_Ship1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Ship1, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ship1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ship1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Ship1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Ship1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Ship2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Ship2, 75);
    lv_obj_set_height(ui_Ship2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ship2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ship2, "A2");
    lv_obj_add_flag(ui_Ship2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Ship2, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ship2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ship2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Ship2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Ship2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Ship3 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Ship3, 75);
    lv_obj_set_height(ui_Ship3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ship3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ship3, "A3");
    lv_obj_add_flag(ui_Ship3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Ship3, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ship3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ship3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Ship3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Ship3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Ship4 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Ship4, 75);
    lv_obj_set_height(ui_Ship4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ship4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ship4, "A4");
    lv_obj_add_flag(ui_Ship4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Ship4, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ship4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ship4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Ship4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Ship4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

}

void ui_HideShips_screen_destroy(void)
{
    if(ui_HideShips) lv_obj_del(ui_HideShips);

    // NULL screen variables
    ui_HideShips = NULL;
    ui_okButton1 = NULL;
    ui_okButtonLabel1 = NULL;
    ui_Container2 = NULL;
    ui_HideInfo = NULL;
    ui_Ship1 = NULL;
    ui_Ship2 = NULL;
    ui_Ship3 = NULL;
    ui_Ship4 = NULL;

}
