// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Galaxis

#include "../ui.h"

void ui_MainMenu_screen_init(void)
{
ui_MainMenu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MainMenuPanel = lv_obj_create(ui_MainMenu);
lv_obj_set_width( ui_MainMenuPanel, 225);
lv_obj_set_height( ui_MainMenuPanel, 225);
lv_obj_set_align( ui_MainMenuPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainMenuPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainMenuPanel, 115, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MainMenuPanel, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_MainMenuPanel, 152, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_MainMenuPanel, 152, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_MainMenuPanel, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainMenuPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainMenuItem = lv_label_create(ui_MainMenuPanel);
lv_obj_set_width( ui_MainMenuItem, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainMenuItem, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainMenuItem, 0 );
lv_obj_set_y( ui_MainMenuItem, -25 );
lv_obj_set_align( ui_MainMenuItem, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainMenuItem,"Einzel");
lv_obj_set_style_text_color(ui_MainMenuItem, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainMenuItem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainMenuItem, &ui_font_Destruct36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainMenuHint = lv_label_create(ui_MainMenuPanel);
lv_obj_set_width( ui_MainMenuHint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainMenuHint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainMenuHint, 0 );
lv_obj_set_y( ui_MainMenuHint, 39 );
lv_obj_set_align( ui_MainMenuHint, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainMenuHint,"Einzelspieler");

}
