// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Galaxis

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_okButton;
extern lv_obj_t * ui_okButtonLabel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_shouldPlaySounds;
extern lv_obj_t * ui_shouldPlayIdle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

