#
name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write
    
steps:
    - uses: actions/checkout@v4

    - uses: dawidd6/action-download-artifact@v2
      name: Download Firmware
      with:
        workflow: platformio-build.yml
        name: firmware-esp32c3-de
        path: ./app/static/firmware/

    - run: cd /home/runner/work/galaxis/galaxis/app

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: /home/runner/work/galaxis/galaxis/app/package-lock.json

    - name: npm install
      working-directory: /home/runner/work/galaxis/galaxis/app/
      run: npm install

    - name: npm build
      working-directory: ./app/
      run: npm run build --if-present
  
    - uses: actions/upload-pages-artifact@main
      with:
        name: page
        path: ./app/build

    - uses: actions/deploy-pages@main
      with: 
        artifact_name: page
