name: build-platformio

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Galaxis
        working-directory: ./Galaxis
        run: pio run -e seeed_xiao_esp32s3 -e seeed_xiao_esp32c3
        env:
          PLATFORMIO_BUILD_FLAGS: -DDE

      - name: Rename Firmware S3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32s3/
        run: mv firmware.bin firmware-esp32s3-de.bin

      - name: Rename Firmware C3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32c3/
        run: mv firmware.bin firmware-esp32c3-de.bin
    
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32s3/firmware-esp32s3-de.bin
    
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32s3/bootloader.bin

      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32s3/partitions.bin   
    
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32s3/firmware-esp32s3-de.bin
          
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32c3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32c3/firmware-esp32c3-de.bin
  
      - name: Build Galaxis EN
        working-directory: ./Galaxis
        run: pio run -e seeed_xiao_esp32s3 -e seeed_xiao_esp32c3

      - name: Rename Firmware S3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32s3/
        run: mv firmware.bin firmware-esp32s3-en.bin

      - name: Rename Firmware C3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32c3/
        run: mv firmware.bin firmware-esp32c3-en.bin
    
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32s3/firmware-esp32s3-en.bin
    
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32s3/firmware-esp32s3-en.bin

      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32c3-de
          path: ./Galaxis/.pio/build/seeed_xiao_esp32c3/firmware-esp32c3-en.bin
  
