name: build-platformio

on:  
  [push]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Create directory
        run: mkdir ~/firmware-esp32s3/ && mkdir ~/firmware-esp32c3/ 

      - name: Build Galaxis
        working-directory: ./Galaxis
        run: pio run -e seeed_xiao_esp32s3 -e seeed_xiao_esp32c3
        env:
          PLATFORMIO_BUILD_FLAGS: -DDE

      - name: Copy Firmware S3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32s3/
        run: mv *.bin ~/firmware-esp32s3/

      - name: Rename Firmware S3
        working-directory: ~/firmware-esp32s3
        run: mv firmware.bin firmware-de.bin

      - name: Copy Firmware C3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32c3/
        run: mv *.bin ~/firmware-esp32c3/

      - name: Rename Firmware C3
        working-directory: ~/firmware-esp32c3
        run: mv firmware.bin firmware-de.bin
     
    # Build EN Version

      - name: Build Galaxis EN
        working-directory: ./Galaxis
        run: pio run -e seeed_xiao_esp32s3 -e seeed_xiao_esp32c3

      - name: Copy Firmware S3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32s3/
        run: mv firmware.bin ~/firmware-esp32s3/firmware-en.bin

      - name: Copy Firmware C3
        working-directory: ./Galaxis/.pio/build/seeed_xiao_esp32c3/
        run: mv firmware.bin ~/firmware-esp32c3/firmware-en.bin
    
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32c3-de
          path: ~/*.bin
  
